#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

runApplication blockMesh
runApplication postProcess -func writeCellCentres
cd 0
ls -I "C" -I "Cx" -I "Cy" -I "Cz" -I "expressionS" -I "setExpS" -I "setExpV" -I "expressionV"
./setExpS
./setExpV
cd ..
runApplication $application

#------------------------------------------------------------------------------
